version: '3'
services:
 #  appx:
 #   build: ./APPX
    #command: bash  -c "dotnet run --urls https://0.0.0.0:5000"
 #   command: bash  -c "dotnet ef database update"
    #volumes:
    #   - .:/myapp
 #   ports:
 #     - "5000:5000"
    #  - "5001:5001"
  #  depends_on:
  #    - db 
  ### MySQL ################################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
 #   networks:
 #     - backend

  #workspace:
  #      build:
  #        context: ./workspace
  #        args:
  #        - INSTALL_MSSQL=${WORKSPACE_INSTALL_MSSQL}
  #        - INSTALL_MYSQL_CLIENT=${WORKSPACE_INSTALL_MYSQL_CLIENT}
  
   #nginx:
   #  build: ./NGINX
    #volumes:
    #  - /var/lib/postgresql/data
    # ports:
    #  - "80:80"
    # depends_on:
    #  - appx 